"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import {
  Bookmark,
  Copy,
  MessageSquareText,
  MoreHorizontal,
  Plus,
  Sparkles,
  Star,
  Users,
  WandSparkles,
} from "lucide-react";
import { api } from "@/lib/api";
import { DashboardEmpty, formatNumber, PageHead, PanelError, PanelLoading, relativeTime } from "./shared";

export function Overview({ role, token, user }) {
  const [range, setRange] = useState(6);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [reload, setReload] = useState(0);

  useEffect(() => {
    let active = true;
    setLoading(true);
    setError("");
    api.dashboard(token, range)
      .then((response) => {
        if (active)
          setData(response);
      })
      .catch((requestError) => {
        if (active)
          setError(requestError instanceof Error ? requestError.message : "Could not load dashboard");
      })
      .finally(() => {
        if (active)
          setLoading(false);
      });
    return () => {
      active = false;
    };
  }, [token, range, reload]);

  const cards = useMemo(() => buildCards(role, data?.stats), [role, data]);
  const title = role === "admin" ? `Welcome back, ${user.name.split(" ")[0]}.` : `Good ${dayPart()}, ${user.name.split(" ")[0]}.`;

  return (
    <>
      <PageHead
        eyebrow={role === "admin" ? "Admin command center" : role === "creator" ? "Creator dashboard" : "Your dashboard"}
        title={title}
        copy={role === "admin" ? "Review live marketplace activity and manage PromptArc from one workspace." : "Everything here is calculated from your account and database records."}
        action={<Link className="button" href="/dashboard/add-prompt"><Plus /> {role === "admin" ? "Add admin prompt" : "New prompt"}</Link>}
      />

      {loading && !data ? <PanelLoading label="Calculating dashboard totals…" /> : error && !data ? <PanelError message={error} onRetry={() => setReload((value) => value + 1)} /> : (
        <>
          {error && <div className="dashboard-inline-error">{error}<button onClick={() => setReload((value) => value + 1)}>Retry</button></div>}
          <div className="stat-grid">
            {cards.map(({ label, value, note, icon: Icon }) => <article key={label}><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div><i><Icon /></i></article>)}
          </div>

          <div className="dashboard-two-col">
            <section className="dashboard-panel chart-panel">
              <div className="panel-head">
                <div><h2>{role === "admin" ? "Marketplace growth" : "Prompt performance"}</h2><p>{role === "admin" ? "Prompts and cumulative copies by creation month" : "Copies generated by prompts created in each month"}</p></div>
                <select value={range} onChange={(event) => setRange(Number(event.target.value))} aria-label="Chart range">
                  <option value={6}>Last 6 months</option>
                  <option value={12}>Last 12 months</option>
                </select>
              </div>
              <div className="chart-wrap">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={data?.chart || []}>
                    <defs><linearGradient id={`copyFill-${role}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff7557" stopOpacity={0.35} /><stop offset="100%" stopColor="#ff7557" stopOpacity={0} /></linearGradient></defs>
                    <CartesianGrid strokeDasharray="4 4" vertical={false} />
                    <XAxis dataKey="label" axisLine={false} tickLine={false} />
                    <YAxis axisLine={false} tickLine={false} allowDecimals={false} />
                    <Tooltip />
                    <Area type="monotone" dataKey="copies" stroke="#ff7557" strokeWidth={3} fill={`url(#copyFill-${role})`} />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </section>

            <section className="dashboard-panel activity-panel">
              <div className="panel-head"><div><h2>Recent activity</h2><p>Notifications generated by real account actions</p></div><MoreHorizontal /></div>
              {data?.activities?.length ? data.activities.map((activity, index) => (
                <div className="activity-item" key={activity._id}>
                  <span className={`activity-icon activity-${index % 4}`}><Sparkles /></span>
                  <div><p><strong>{activity.title}</strong> {activity.message}</p><small>{relativeTime(activity.createdAt)}</small></div>
                </div>
              )) : <DashboardEmpty title="No activity yet" copy="Submissions, reviews, bookmarks, and moderation updates will appear here." />}
            </section>
          </div>

          <section className="dashboard-panel top-prompts">
            <div className="panel-head">
              <div><h2>{role === "admin" ? "Top marketplace prompts" : "Top-performing prompts"}</h2><p>Ranked from current database totals</p></div>
              <Link href={role === "admin" ? "/dashboard/all-prompts" : "/dashboard/my-prompts"}>View all</Link>
            </div>
            {data?.topPrompts?.length ? <OverviewPromptRows prompts={data.topPrompts} /> : <DashboardEmpty title="No prompts yet" copy="Publish a prompt to start collecting copies, saves, and ratings." action={<Link className="button button-sm" href="/dashboard/add-prompt"><Plus /> Add prompt</Link>} />}
          </section>
        </>
      )}
    </>
  );
}

export function Analytics({ role, token }) {
  const [range, setRange] = useState(6);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [reload, setReload] = useState(0);

  useEffect(() => {
    let active = true;
    setLoading(true);
    setError("");
    const promise = role === "admin" ? api.adminAnalytics(token, range) : api.dashboard(token, range);
    promise.then((response) => {
      if (active)
        setData(response);
    }).catch((requestError) => {
      if (active)
        setError(requestError instanceof Error ? requestError.message : "Could not load analytics");
    }).finally(() => {
      if (active)
        setLoading(false);
    });
    return () => {
      active = false;
    };
  }, [role, token, range, reload]);

  const stats = role === "admin" ? data || {} : data?.stats || {};
  const growth = role === "admin" ? data?.growth || [] : data?.chart || [];
  const shares = data?.toolShare || [];
  const shareTotal = shares.reduce((sum, item) => sum + Number(item.value || 0), 0);
  const cards = role === "admin" ? [
    { label: "Total users", value: formatNumber(stats.totalUsers), icon: Users },
    { label: "Total prompts", value: formatNumber(stats.totalPrompts), icon: WandSparkles },
    { label: "Total reviews", value: formatNumber(stats.totalReviews), icon: MessageSquareText },
    { label: "Total copies", value: formatNumber(stats.totalCopies), icon: Copy },
  ] : [
    { label: "Your prompts", value: formatNumber(stats.totalPrompts), icon: WandSparkles },
    { label: "Total copies", value: formatNumber(stats.totalCopies), icon: Copy },
    { label: "Total bookmarks", value: formatNumber(stats.totalBookmarks), icon: Bookmark },
    { label: "Average rating", value: Number(stats.averageRating || 0).toFixed(1), icon: Star },
  ];

  return (
    <>
      <PageHead
        eyebrow={role === "admin" ? "Marketplace intelligence" : "Creator intelligence"}
        title="Analytics"
        copy="All metrics are aggregated from current MongoDB records."
        action={<label className="head-select">Range<select value={range} onChange={(event) => setRange(Number(event.target.value))}><option value={6}>6 months</option><option value={12}>12 months</option></select></label>}
      />
      {loading && !data ? <PanelLoading label="Building analytics…" /> : error && !data ? <PanelError message={error} onRetry={() => setReload((value) => value + 1)} /> : (
        <>
          <div className="stat-grid">{cards.map(({ label, value, icon: Icon }) => <article key={label}><div><span>{label}</span><strong>{value}</strong><small>Live total</small></div><i><Icon /></i></article>)}</div>
          <div className="dashboard-two-col analytics-grid">
            <section className="dashboard-panel chart-panel">
              <div className="panel-head"><div><h2>Prompt growth</h2><p>New prompts by month</p></div></div>
              <div className="chart-wrap">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={growth}>
                    <CartesianGrid strokeDasharray="4 4" vertical={false} />
                    <XAxis dataKey="label" axisLine={false} tickLine={false} />
                    <YAxis axisLine={false} tickLine={false} allowDecimals={false} />
                    <Tooltip />
                    <Line type="monotone" dataKey="prompts" stroke="#b9e641" strokeWidth={3} dot={{ fill: "#0f1720", strokeWidth: 2 }} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </section>
            <section className="dashboard-panel tool-share">
              <div className="panel-head"><div><h2>AI tool share</h2><p>Prompts grouped by AI tool</p></div></div>
              {shares.length ? shares.map((item) => {
                const percent = shareTotal ? Math.round((item.value / shareTotal) * 100) : 0;
                return <div key={item.label}><span>{item.label}</span><div><i style={{ width: `${percent}%` }} /></div><strong>{percent}%</strong></div>;
              }) : <DashboardEmpty title="No tool data" copy="Tool share appears after prompts are added." />}
            </section>
          </div>
        </>
      )}
    </>
  );
}

function OverviewPromptRows({ prompts }) {
  return (
    <div className="responsive-table">
      <table>
        <thead><tr><th>Prompt</th><th>Status</th><th>Copies</th><th>Saves</th><th>Rating</th></tr></thead>
        <tbody>{prompts.map((prompt) => <tr key={prompt._id}><td><div className="table-prompt-icon">{String(prompt.aiTool || "P").slice(0, 1)}</div><div><Link href={`/prompts/${prompt._id}`}><strong>{prompt.title}</strong></Link><small>{prompt.creator?.name || prompt.aiTool} · {prompt.category}</small></div></td><td><span className={`status ${prompt.status || "approved"}`}>{prompt.status || "approved"}</span></td><td>{formatNumber(prompt.copyCount)}</td><td>{formatNumber(prompt.bookmarkCount)}</td><td>{Number(prompt.averageRating || 0).toFixed(1)}</td></tr>)}</tbody>
      </table>
    </div>
  );
}

function buildCards(role, stats = {}) {
  if (role === "admin") {
    return [
      { label: "Total users", value: formatNumber(stats.totalUsers), note: `${formatNumber(stats.pendingPrompts)} pending prompts`, icon: Users },
      { label: "Total prompts", value: formatNumber(stats.totalPrompts), note: `${formatNumber(stats.openReports)} open reports`, icon: WandSparkles },
      { label: "Total reviews", value: formatNumber(stats.totalReviews), note: "All marketplace reviews", icon: MessageSquareText },
      { label: "Total copies", value: formatNumber(stats.totalCopies), note: `${formatNumber(stats.totalBookmarks)} saves`, icon: Copy },
    ];
  }
  if (role === "creator") {
    return [
      { label: "Your prompts", value: formatNumber(stats.totalPrompts), note: "All submission states", icon: WandSparkles },
      { label: "Total copies", value: formatNumber(stats.totalCopies), note: "Across your prompts", icon: Copy },
      { label: "Bookmarks", value: formatNumber(stats.totalBookmarks), note: "Saves by members", icon: Bookmark },
      { label: "Average rating", value: Number(stats.averageRating || 0).toFixed(1), note: "Across rated prompts", icon: Star },
    ];
  }
  return [
    { label: "Your prompts", value: formatNumber(stats.totalPrompts), note: "Free plan limit applies", icon: WandSparkles },
    { label: "Prompt copies", value: formatNumber(stats.totalCopies), note: "Across your prompts", icon: Copy },
    { label: "Saved prompts", value: formatNumber(stats.savedCount), note: "Your bookmark library", icon: Bookmark },
    { label: "Reviews written", value: formatNumber(stats.reviewCount), note: "Your contributions", icon: MessageSquareText },
  ];
}

function dayPart() {
  const hour = new Date().getHours();
  if (hour < 12)
    return "morning";
  if (hour < 18)
    return "afternoon";
  return "evening";
}
