const creators = [
    { _id: "c1", name: "Nadia Rahman", email: "nadia@promptarc.dev" },
    { _id: "c2", name: "Ethan Cole", email: "ethan@promptarc.dev" },
    { _id: "c3", name: "Maya Chen", email: "maya@promptarc.dev" },
    { _id: "c4", name: "Ari Mensah", email: "ari@promptarc.dev" },
];
export const demoPrompts = [
    {
        _id: "strategy-copilot",
        title: "Turn a messy brief into a sharp product strategy",
        description: "A structured product-strategy copilot that exposes assumptions, maps opportunities, and produces a decision-ready one-pager.",
        content: "Act as a senior product strategist. I will share an unstructured brief. First, extract the customer, problem, desired outcome, constraints, and unknowns. Then ask up to five high-leverage questions. Finally produce: (1) problem framing, (2) opportunity map, (3) three strategic options with trade-offs, (4) recommended direction, (5) 30-day validation plan. Brief: {{PASTE BRIEF}}",
        category: "Productivity",
        aiTool: "ChatGPT",
        tags: ["strategy", "product", "planning"],
        difficulty: "Intermediate",
        visibility: "public",
        creator: creators[0],
        copyCount: 2847,
        bookmarkCount: 912,
        averageRating: 4.9,
        reviewCount: 184,
        featured: true,
        status: "approved",
        createdAt: "2026-08-18T08:00:00.000Z",
        usageInstructions: "Replace the brief placeholder with raw notes, an email, or a meeting transcript. For the strongest output, answer the clarification questions before requesting the final plan.",
    },
    {
        _id: "cinematic-worldbuilder",
        title: "Cinematic world-builder for Midjourney",
        description: "Compose visually coherent scenes with precise lighting, lens, palette, atmosphere, and narrative details.",
        content: "Create a cinematic still of {{SUBJECT}} in {{SETTING}}, visual tension: {{TENSION}}. Shot on {{LENS}}, {{CAMERA ANGLE}}, lighting by {{LIGHT SOURCE}}, palette of {{PALETTE}}, tactile details, atmospheric depth, restrained composition, photoreal, editorial color grade --ar 16:9 --stylize 250",
        category: "Design",
        aiTool: "Midjourney",
        tags: ["cinematic", "art direction", "visual"],
        difficulty: "Pro",
        visibility: "private",
        creator: creators[2],
        copyCount: 2310,
        bookmarkCount: 801,
        averageRating: 4.8,
        reviewCount: 129,
        featured: true,
        status: "approved",
        createdAt: "2026-08-19T08:00:00.000Z",
        usageInstructions: "Keep the tension statement short and visual. Test two lens choices before changing the style value.",
        isLocked: true,
    },
    {
        _id: "research-synthesizer",
        title: "Evidence-first research synthesizer",
        description: "Convert a source pack into findings, contradictions, confidence ratings, and practical recommendations.",
        content: "You are an evidence synthesis analyst. Work only from the supplied source pack. Build an evidence table with claim, source, strength, limitations, and contradictions. Separate facts from inference. Then write an executive synthesis with confidence labels and five next actions. Source pack: {{SOURCES}}",
        category: "Research",
        aiTool: "Claude",
        tags: ["research", "evidence", "analysis"],
        difficulty: "Intermediate",
        visibility: "public",
        creator: creators[1],
        copyCount: 1988,
        bookmarkCount: 677,
        averageRating: 4.9,
        reviewCount: 143,
        featured: true,
        status: "approved",
        createdAt: "2026-08-20T08:00:00.000Z",
        usageInstructions: "Paste source text with clear labels. Ask for a CSV evidence table if you plan to continue the analysis in a spreadsheet.",
    },
    {
        _id: "brand-voice-system",
        title: "Build a reusable brand voice system",
        description: "Turn a handful of examples into a concrete voice guide, vocabulary map, and QA checklist.",
        content: "Analyze the writing samples below and infer a brand voice system. Return: personality traits, rhythm, sentence patterns, vocabulary to use, vocabulary to avoid, tone shifts by channel, before/after examples, and a 10-point QA checklist. Do not imitate phrases verbatim. Samples: {{SAMPLES}}",
        category: "Marketing",
        aiTool: "Gemini",
        tags: ["brand", "copywriting", "voice"],
        difficulty: "Beginner",
        visibility: "public",
        creator: creators[3],
        copyCount: 1754,
        bookmarkCount: 620,
        averageRating: 4.7,
        reviewCount: 118,
        featured: true,
        status: "approved",
        createdAt: "2026-08-16T08:00:00.000Z",
    },
    {
        _id: "debugging-navigator",
        title: "Root-cause debugging navigator",
        description: "Diagnose software defects systematically without jumping to the first plausible fix.",
        content: "Act as a debugging partner. From the symptoms and code I provide: restate expected vs actual behavior, list hypotheses ranked by likelihood, identify the smallest discriminating test for each, and wait for results. Only then propose the minimal fix, regression tests, and prevention note. Context: {{CONTEXT}}",
        category: "Development",
        aiTool: "ChatGPT",
        tags: ["debugging", "engineering", "code"],
        difficulty: "Pro",
        visibility: "public",
        creator: creators[1],
        copyCount: 1602,
        bookmarkCount: 584,
        averageRating: 4.8,
        reviewCount: 97,
        featured: true,
        status: "approved",
        createdAt: "2026-08-21T08:00:00.000Z",
    },
    {
        _id: "lesson-architect",
        title: "Adaptive lesson architect",
        description: "Design a lesson around learner level, misconceptions, retrieval practice, and observable outcomes.",
        content: "Design a {{DURATION}} lesson on {{TOPIC}} for {{LEARNER}}. Include: prerequisite check, one clear objective, misconception forecast, concise explanation, worked example, guided practice, retrieval questions, transfer task, and an exit ticket with rubric. Adapt language to {{LEVEL}}.",
        category: "Education",
        aiTool: "Claude",
        tags: ["teaching", "lesson", "learning"],
        difficulty: "Beginner",
        visibility: "public",
        creator: creators[0],
        copyCount: 1441,
        bookmarkCount: 498,
        averageRating: 4.7,
        reviewCount: 89,
        featured: true,
        status: "approved",
        createdAt: "2026-08-14T08:00:00.000Z",
    },
    {
        _id: "meeting-to-momentum",
        title: "Meeting notes to momentum",
        description: "Extract decisions, owners, deadlines, open questions, and a follow-up message from raw meeting notes.",
        content: "Transform these meeting notes into: decisions made, action items with owner and due date, risks, unresolved questions, and a concise follow-up email. Flag any owner or deadline that is missing rather than inventing it. Notes: {{NOTES}}",
        category: "Productivity",
        aiTool: "Gemini",
        tags: ["meetings", "actions", "operations"],
        difficulty: "Beginner",
        visibility: "public",
        creator: creators[3],
        copyCount: 1310,
        bookmarkCount: 455,
        averageRating: 4.6,
        reviewCount: 72,
        createdAt: "2026-08-15T08:00:00.000Z",
    },
    {
        _id: "conversion-lab",
        title: "Landing page conversion lab",
        description: "Critique a landing page through clarity, relevance, proof, friction, and motivation - then rewrite the weak parts.",
        content: "Audit this landing page for conversion. Score clarity, relevance, proof, friction, motivation, and accessibility from 1-10 with evidence. Identify the three highest-impact changes. Rewrite the hero, proof section, and CTA while preserving the brand voice. Page copy: {{COPY}}",
        category: "Marketing",
        aiTool: "ChatGPT",
        tags: ["conversion", "landing page", "CRO"],
        difficulty: "Intermediate",
        visibility: "private",
        creator: creators[2],
        copyCount: 1195,
        bookmarkCount: 430,
        averageRating: 4.8,
        reviewCount: 83,
        createdAt: "2026-08-12T08:00:00.000Z",
        isLocked: true,
    },
];
export const demoReviews = [
    { _id: "r1", user: { name: "Sofia Malik" }, rating: 5, comment: "The structure forces better thinking before the model starts writing. It replaced three separate templates for our team.", createdAt: "2026-08-20T12:00:00.000Z" },
    { _id: "r2", user: { name: "Jon Bell" }, rating: 5, comment: "Finally, prompts that explain when and how to use them. The quality bar feels noticeably higher here.", createdAt: "2026-08-19T12:00:00.000Z" },
    { _id: "r3", user: { name: "Tania Ahmed" }, rating: 4, comment: "Filtering by tool and difficulty makes it easy to find something useful in under a minute.", createdAt: "2026-08-18T12:00:00.000Z" },
];
export const demoCreators = [
    { _id: "c1", name: "Nadia Rahman", specialty: "Product systems", promptCount: 48, totalCopies: 18420, initials: "NR" },
    { _id: "c2", name: "Ethan Cole", specialty: "Research & code", promptCount: 41, totalCopies: 15980, initials: "EC" },
    { _id: "c3", name: "Maya Chen", specialty: "Visual direction", promptCount: 36, totalCopies: 14310, initials: "MC" },
    { _id: "c4", name: "Ari Mensah", specialty: "Growth writing", promptCount: 33, totalCopies: 12860, initials: "AM" },
];
export const dashboardGrowth = [
    { label: "Mar", prompts: 3, copies: 310 },
    { label: "Apr", prompts: 5, copies: 520 },
    { label: "May", prompts: 7, copies: 680 },
    { label: "Jun", prompts: 8, copies: 1040 },
    { label: "Jul", prompts: 11, copies: 1460 },
    { label: "Aug", prompts: 14, copies: 1980 },
];
